version: '3'
services:
  coder:
      image: (
      
      ports:
        - '80:80'
        - '8080:8080'
        - '3000:3000'
      user: root
      volumes: 
        - $HOME:/home/coder/project
      command:
        - "--auth=none"
        - "--install-extension ms-ceintl.vscode-language-pack-ja"
