version: '3'
services:
  coder:
      image: codercom/code-server
      ports:
        - '80:80'
        - '8080:8080'
        - '3000:3000'
      user:
        - "${UID}:${GID}"
      volumes: 
        - $HOME:/home/coder/project
      command:
        - "--auth=none"
