version: '3.2'
services:
  coder:
      image: nasoasam/cs
      ports:
        - '80:80'
        - '8080:8080'
        - '3000:3000'
      user: root
      volumes: 
        - $HOME:/home/coder/project
        - type: bind
          source: $HOME/certs
          target: /certs
      command:
        - "--auth=none"
        - "--cert=/certs/my-cert.crt"
        - "--cert-key=/certs/my-cert.key"
